security:
  user:
    name: john
    password: P@ssw0rd
spring:
  application:
    name: Spring Boot Cart
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: false
        page-parameter: page
        prefix: ''
        qualifier-delimiter: _
        size-parameter: size
      sort:
        sort-parameter: sort
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/shoppingcart_java?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  thymeleaf:
    encoding: utf-8